name: CI

on:
  push:
    branches:
      - master  # Change this to your default branch
  pull_request:
    branches:
      - master  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'  # Change to your desired Python version
          
      - name: Install dependencies
        run: |
          cd API
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd API
          pytest tests

      - name: Train model
        run: |
          cd API
          python train_model.py || exit 0 
